# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1994637f09c689edf3ddecaf3df3457e674e4baf21b806e7304a6d05503da030926a2ed2bc89b97af3306e71bc9000ccd622c42b9560077e218b92482f31afd1

test:
  secret_key_base: 59553212e2acfeca2744a58b5b4a6c370fff9a9e15ebdf6b501ae5c8ab92612ad4cc1ec5decd716dd8a6c950d4165430d4659fb2f705a0223d52737358b14540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
